module.exports = [
  {
        id: "1",
        type:"anime",
        title: "One Punch Man",
        genres: "Action, Comedy",
        img: 'https://occ-0-1722-1723.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABaazw-uLC_MreJganqQyppcCRzItLXqsTSTvhJqIe_NIkZTzOYL_JgeABTgvUBhBHSAqj2rK81tesT5wV3bmvlSaxLxO.jpg?r=0e5',
        video: "https://www.youtube.com/watch?v=Poo5lqoWSGw",
    },
    {
        id: "2",
        type:"anime",
        title: "My Hero Academia",
        genres: "Action",
        img: 'https://www.online-station.net/wp-content/uploads/2020/12_1/1200x630-36.jpg',
        video: "https://www.youtube.com/watch?v=ZclBluzAZVE",
    },
    {
        id: "3",
        type:"anime",
        title: "Demon Slayer: Kimetsu no Yaiba",
        genres: "Action",
        img: 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/6079/1106079-h-030e4e497037',
        video: "https://www.youtube.com/watch?v=2MKkj1DQ0NU",
    }, {
        id: "4",
        type:"anime",
        title: "Attack On Titan",
        genres: "Action",
        img: 'https://static.thairath.co.th/media/4DQpjUtzLUwmJZZSCIfgbsJKUu22peTAyYvZZbrHqKWV.jpg',
        video: "https://www.youtube.com/watch?v=JIcNSBLw_nA",
    },
    {
        id: '5',
        type:"anime",
        title: "Sword Art Online",
        genres: "Action",
        img: 'https://i1.wp.com/www.thailandesportclub.com/wp-content/uploads/2019/12/00-39.jpg',
        video: "https://www.youtube.com/watch?v=2ghqDZGGBGw",
    }, {
        id: '6',
        type:"anime",
        title: "One Punch Man",
        genres: "Action, Comedy",
        img: 'https://occ-0-1722-1723.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABaazw-uLC_MreJganqQyppcCRzItLXqsTSTvhJqIe_NIkZTzOYL_JgeABTgvUBhBHSAqj2rK81tesT5wV3bmvlSaxLxO.jpg?r=0e5',
        video: "https://www.youtube.com/watch?v=Poo5lqoWSGw",
    },
    {
        id: '7',
        type:"anime",
        title: "My Hero Academia",
        genres: "Action",
        img: 'https://www.online-station.net/wp-content/uploads/2020/12_1/1200x630-36.jpg',
        video: "https://www.youtube.com/watch?v=ZclBluzAZVE",
    },
    {
        id: '8',
        title: "Demon Slayer",
        genres: "Action",
        img: 'https://img1.hotstarext.com/image/upload/f_auto,t_web_m_1x/sources/r1/cms/prod/6079/1106079-h-030e4e497037',
        video: "https://www.youtube.com/watch?v=2MKkj1DQ0NU",
    }, {
        id: '9',
        type:"anime",
        title: "Attack On Titan",
        genres: "Action",
        img: 'https://static.thairath.co.th/media/4DQpjUtzLUwmJZZSCIfgbsJKUu22peTAyYvZZbrHqKWV.jpg',
        video: "https://www.youtube.com/watch?v=JIcNSBLw_nA",
    },
    {
        id: '10',
        type:"anime",
        title: "Sword Art Online",
        genres: "Action",
        img: 'https://i1.wp.com/www.thailandesportclub.com/wp-content/uploads/2019/12/00-39.jpg',
        video: "https://www.youtube.com/watch?v=2ghqDZGGBGw",
    },
      {
        id: '11',
        type: "movie",
        title: "Iron Man",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images.alphacoders.com/270/thumbbig-270963.webp',
        video: "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    },
    {
        id: '12',
        type: "movie",
        title: "The Dark Knight",
        genres: "Action, Crime, Drama",
        img: 'https://images4.alphacoders.com/573/thumbbig-57394.webp',
        video: "https://www.youtube.com/watch?v=LDG9bisJEaI",
    },
    {
        id: '13',
        type: "movie",
        title: "The Avengers",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images5.alphacoders.com/573/thumbbig-573475.webp',
        video: "https://www.youtube.com/watch?v=eOrNdBpGMv8",
    }, {
        id: '14',
        type: "movie",
        title: "Star Wars",
        genres: "Action, Adventure",
        img: 'https://images4.alphacoders.com/653/thumbbig-653613.webp',
        video: "https://www.youtube.com/watch?v=sGbxmsDFVnE",
    }, {
        id: '15',
        type: "movie",
        title: "The Lord of the Rings",
        genres: "Action, Fantasy",
        img: 'https://cdn.wallpapersafari.com/70/69/JhB6yH.jpg',
        video: "https://www.youtube.com/watch?v=HX4KKkSKZAY",
    }, {
        id: '16',
        type: "movie",
        title: "Iron Man",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images.alphacoders.com/270/thumbbig-270963.webp',
        video: "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    },
    {
        id: '17',
        type: "movie",
        title: "The Dark Knight",
        genres: "Action, Crime, Drama",
        img: 'https://images4.alphacoders.com/573/thumbbig-57394.webp',
        video: "https://www.youtube.com/watch?v=LDG9bisJEaI",
    },
    {
        id: '18',
        type: "movie",
        title: "The Avengers",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images5.alphacoders.com/573/thumbbig-573475.webp',
        video: "https://www.youtube.com/watch?v=eOrNdBpGMv8",
    }, {
        id: '19',
        type: "movie",
        title: "Star Wars",
        genres: "Action, Adventure",
        img: 'https://images4.alphacoders.com/653/thumbbig-653613.webp',
        video: "https://www.youtube.com/watch?v=sGbxmsDFVnE",
    }, {
        id: '20',
        type: "movie",
        title: "The Lord of the Rings",
        genres: "Action, Fantasy",
        img: 'https://cdn.wallpapersafari.com/70/69/JhB6yH.jpg',
        video: "https://www.youtube.com/watch?v=HX4KKkSKZAY",
    },
      {
        id: '21',
        type: "series",
        title: "Squid Game",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images.workpointnews.com/workpointnews/2021/10/22103724/1634873841_98196_web_bizview26.jpg',
        video: "https://www.youtube.com/watch?v=oqxAJKy0ii4",
    },
    {
        id: '22',
        type: "series",
        title: "Alice in Wonderland",
        genres: "Action, Crime, Drama",
        img: 'https://f.ptcdn.info/258/072/000/qmxh487kd7B36r3bqbtT-o.jpg',
        video: "https://www.youtube.com/watch?v=49_44FFKZ1M",
    },
    {
        id: '23',
        type: "series",
        title: "Game of Thrones",
        genres: "Action, Fantasy, Drama",
        img: 'https://www.matichon.co.th/wp-content/uploads/2019/05/g06.jpg',
        video: "https://www.youtube.com/watch?v=KPLWWIOCOOQ",
    }, {
        id: '24',
        type: "series",
        title: "Start Up",
        genres: "Drama, Romantic",
        img: 'https://1.bp.blogspot.com/-WXyCfxszUN0/X84Hh0hsIQI/AAAAAAAAdIA/CQfZEeXG1xQDJTP7u4uxEGz6vrImxmH7ACPcBGAsYHg/s1241/IMG_1398.JPG',
        video: "https://www.youtube.com/watch?v=BemKyzbLDDc",
    }, {
        id: '25',
        type: "series",
        title: "Iron Man",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images.alphacoders.com/270/thumbbig-270963.webp',
        video: "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    }, {
        id: '26',
        type: "series",
        title: "Squid Game",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images.workpointnews.com/workpointnews/2021/10/22103724/1634873841_98196_web_bizview26.jpg',
        video: "https://www.youtube.com/watch?v=oqxAJKy0ii4",
    },
    {
        id: '27',
        type: "series",
        title: "Alice in Wonderland",
        genres: "Action, Crime, Drama",
        img: 'https://f.ptcdn.info/258/072/000/qmxh487kd7B36r3bqbtT-o.jpg',
        video: "https://www.youtube.com/watch?v=49_44FFKZ1M",
    },
    {
        id: '28',
        type: "series",
        title: "Game of Thrones",
        genres: "Action, Fantasy, Drama",
        img: 'https://www.matichon.co.th/wp-content/uploads/2019/05/g06.jpg',
        video: "https://www.youtube.com/watch?v=KPLWWIOCOOQ",
    }, {
        id: '29',
        type: "series",
        title: "Start Up",
        genres: "Drama, Romantic",
        img: 'https://1.bp.blogspot.com/-WXyCfxszUN0/X84Hh0hsIQI/AAAAAAAAdIA/CQfZEeXG1xQDJTP7u4uxEGz6vrImxmH7ACPcBGAsYHg/s1241/IMG_1398.JPG',
        video: "https://www.youtube.com/watch?v=BemKyzbLDDc",
    }, {
        id: '30',
        type: "series",
        title: "Iron Man",
        genres: "Action, Adventure, Sci-Fi",
        img: 'https://images.alphacoders.com/270/thumbbig-270963.webp',
        video: "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    }
  
]
